Improve scripts to launch NXP MCUXpresso config tools as generator

diff --git a/scripts/MCUXpresso_Config_Tools/linux-amd64/launch-MCUXpressoConfigTools b/scripts/MCUXpresso_Config_Tools/linux-amd64/launch-MCUXpressoConfigTools
--- a/scripts/MCUXpresso_Config_Tools/linux-amd64/launch-MCUXpressoConfigTools
+++ b/scripts/MCUXpresso_Config_Tools/linux-amd64/launch-MCUXpressoConfigTools
@@ -1,20 +1,16 @@
 #!/bin/bash
-# Script launch MCUXpresso Config Tools in OpenCMSIS generator mode on Ubuntu. It is supported since MCUXpresso Config Tools v16
+# Launch MCUXpresso Config Tools in OpenCMSIS generator mode on Ubuntu. It supports MCUXpresso Config Tools v16 and newer.
 
-# path to .cbuild-gen.idx.yml file
+# Path to .cbuild-gen.idx.yml file
 idxFile=$1
 
-# Find all applications with the given package identifier
+# Get Config Tools Location
 package_id="mcuxpresso-config"
-apps=$(ls /usr/share/applications | grep -i "$package_id")
-#if [ ${#apps[@]} -eq 0 ]; then
-if  [ -z "@apps" ]; then
-  echo "No apps found"
-  exit 1
-fi
-# Find the latest
 latest_app=""
 latest_version="0"
+# Find all applications with the given package identifier
+apps=$(ls /usr/share/applications | grep -i "$package_id")
+# Find the latest
 for app in $apps; do
   version=$(grep -i "Version" /usr/share/applications/$app | cut -d '=' -f 2)
   if [ -z "$version" ]; then
@@ -25,6 +21,12 @@ for app in $apps; do
     latest_app="$app"
   fi
 done
+
+# Exit script if config tools are not found
+if  [[ -z "$latest_app" ]]; then
+  echo "MCUXpresso config tools were not found!"
+  exit 1
+fi
 tools_path=$(grep -i "Exec" /usr/share/applications/$latest_app | cut -d '=' -f 2-)
 tools_folder=$(grep -i "Path" /usr/share/applications/$latest_app | cut -d '=' -f 2-)
 
